# Generated by Django 4.0.1 on 2022-04-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='product',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
