# Generated by Django 4.0.1 on 2022-05-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_blog_id_alter_products_mst_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='id',
            new_name='id_num',
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
